name: Generate Documentation

on:
  push:
    branches:
      - main  # Запускать только для ветки main
  pull_request:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    # Проверка кода из репозитория
    - name: Checkout code
      uses: actions/checkout@v3

    # Установка Doxygen
    - name: Install Doxygen
      run: sudo apt-get install -y doxygen graphviz

    # Генерация документации
    - name: Generate Documentation
      run: doxygen Doxyfile

    # Загрузка документации в ветку gh-pages
    - name: Deploy Documentation to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html  # Папка, куда Doxygen сохранил HTML-документацию
