name: CI Workflow

# Определение событий для запуска workflow
on:
  push:                 # Запуск на каждый push
    branches:
      - main            # Основная ветка
      - development     # Ветка для разработки
  pull_request:         # Запуск на создание Pull Request
    branches:
      - main

# Определение рабочих задач (jobs)
jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Среда выполнения (Ubuntu Linux)

    steps:
    - name: Checkout code   # Шаг 1: Клонирование репозитория
      uses: actions/checkout@v3

    - name: Set up Node.js  # Шаг 2: Установка Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Версия Node.js (замените на вашу)

    - name: Install dependencies  # Шаг 3: Установка зависимостей
      run: npm install

    - name: Run tests       # Шаг 4: Запуск тестов
      run: npm test
